### ISSUE TITLE
After installing via pip get "No module named os" error

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#106]
/~ % which NetPyNE-UI
/usr/local/bin/NetPyNE-UI
 /~ % cat /usr/local/bin/NetPyNE-UI
#!/bin/sh
exec jupyter notebook --NotebookApp.default_url=/geppetto --NotebookApp.token='' --library=netpyne_ui
 /~ % lsl /usr/local/bin/NetPyNE-UI
-rwxr-xr-x  1 salvadord  wheel   112B Nov 28 16:18 /usr/local/bin/NetPyNE-UI*
 /~ % NetPyNE-UI
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/usr/local/lib/python3.7/site-packages/site.py", line 3, in __boot
    import os
ImportError: No module named os

**Comment by salvadord** [comment]
Python 3.7.0 (default, Jul 23 2018, 20:24:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os

In [2]:

**Comment by salvadord** [comment]
Solved -- was picking up the py2 version of jupyter due to wrong $PATH
