### ISSUE TITLE
Issue installing on Windows 10

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#113]
I'm trying to install netpyne-ui on Win 10.

Can you help me?

(nrn) c:\Users\Sergio>pip install netpyne-ui
Collecting netpyne-ui
  Using cached https://files.pythonhosted.org/packages/66/4f/8ec4d478062e6ec0e149b36509f3608dfb6472b876ad626a1e7f8dd72ba6/netpyne_ui-0.5.2.tar.gz
Collecting jupyter_geppetto==0.4.2 (from netpyne-ui)
Collecting netpyne==0.9.1.1 (from netpyne-ui)
  Using cached https://files.pythonhosted.org/packages/28/a9/d75e5240c7a0dbc29644b59cee618cd658a0c330fae2c7decebe5b3b50ec/netpyne-0.9.1.1-py2.py3-none-any.whl
Requirement already satisfied: traitlets==4.3.2 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (4.3.2)
Requirement already satisfied: jedi==0.12.1 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.12.1)
Requirement already satisfied: numpy==1.15.1 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (1.15.1)
Requirement already satisfied: pytz==2018.5 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (2018.5)
Requirement already satisfied: ipykernel==4.9.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (4.9.0)
Requirement already satisfied: Send2Trash==1.5.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (1.5.0)
Requirement already satisfied: ipython-genutils==0.2.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.2.0)
Requirement already satisfied: html5lib==1.0.1 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (1.0.1)
Requirement already satisfied: nbformat==4.4.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (4.4.0)
Requirement already satisfied: webencodings==0.5.1 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.5.1)
Requirement already satisfied: simplegeneric==0.8.1 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.8.1)
Requirement already satisfied: terminado==0.8.1 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.8.1)
Requirement already satisfied: Pygments==2.2.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (2.2.0)
Requirement already satisfied: appnope==0.1.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.1.0)
Requirement already satisfied: cycler==0.10.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.10.0)
Collecting nbconvert==5.4.0 (from jupyter_geppetto==0.4.2->netpyne-ui)
  Using cached https://files.pythonhosted.org/packages/b5/bb/94c493051d60e5b9c0f7f9a368b324201818c1b1c4cae85d1e49a41846c7/nbconvert-5.4.0-py2.py3-none-any.whl
Requirement already satisfied: decorator==4.3.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (4.3.0)
Requirement already satisfied: jupyter-client==5.2.3 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (5.2.3)
Requirement already satisfied: pandocfilters==1.4.2 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (1.4.2)
Requirement already satisfied: jupyter-core==4.4.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (4.4.0)
Requirement already satisfied: prometheus-client==0.3.1 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.3.1)
Requirement already satisfied: six==1.11.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (1.11.0)
Requirement already satisfied: pyecore==0.8.7 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.8.7)
Collecting ipywidgets==7.4.1 (from jupyter_geppetto==0.4.2->netpyne-ui)
  Using cached https://files.pythonhosted.org/packages/ea/c5/0482342559f0fd24909572fe00bb59b2bae98b22d90aac7950f51a98f555/ipywidgets-7.4.1-py2.py3-none-any.whl
Requirement already satisfied: pyparsing==2.2.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (2.2.0)
Collecting widgetsnbextension==3.4.1 (from jupyter_geppetto==0.4.2->netpyne-ui)
  Using cached https://files.pythonhosted.org/packages/3c/9a/9a690e18e335fc4470a2fa38163774940159375798ba6cce043d5cd94bae/widgetsnbextension-3.4.1-py2.py3-none-any.whl
Requirement already satisfied: pyzmq==17.1.2 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (17.1.2)
Requirement already satisfied: mistune==0.8.3 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.8.3)
Requirement already satisfied: pygeppetto==0.4.2 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.4.2)
Requirement already satisfied: MarkupSafe==1.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (1.0)
Requirement already satisfied: jupyter==1.0.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (1.0.0)
Requirement already satisfied: qtconsole==4.4.1 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (4.4.1)
Requirement already satisfied: parso==0.3.1 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.3.1)
Requirement already satisfied: ordered-set==3.0.1 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (3.0.1)
Requirement already satisfied: lxml==4.2.4 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (4.2.4)
Requirement already satisfied: tornado==5.1 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (5.1)
Requirement already satisfied: python-dateutil==2.7.3 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (2.7.3)
Requirement already satisfied: wcwidth==0.1.7 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.1.7)
Requirement already satisfied: pickleshare==0.7.4 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.7.4)
Requirement already satisfied: Jinja2==2.10 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (2.10)
Requirement already satisfied: jupyter-console==5.2.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (5.2.0)
Requirement already satisfied: ipython==6.5.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (6.5.0)
Collecting pexpect==4.6.0 (from jupyter_geppetto==0.4.2->netpyne-ui)
  Using cached https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl
Requirement already satisfied: backcall==0.1.0 in c:\users\sergio\anaconda3\envs\nrn\lib\site-packages (from jupyter_geppetto==0.4.2->netpyne-ui) (0.1.0)
Collecting notebook==5.6.0 (from jupyter_geppetto==0.4.2->netpyne-ui)
  Using cached https://files.pythonhosted.org/packages/5e/7c/7fd8e9584779d65dfcad9fa2e09c76131a41f999f853a9c7026ed8585586/notebook-5.6.0-py2.py3-none-any.whl

....

 creating build\bdist.win-amd64\wheel\netpyne_ui\tests\tut4
  copying build\lib\netpyne_ui\tests\tut4\tut4.py -> build\bdist.win-amd64\wheel\.\netpyne_ui\tests\tut4
  copying build\lib\netpyne_ui\tests\tut4\__init__.py -> build\bdist.win-amd64\wheel\.\netpyne_ui\tests\tut4
  copying build\lib\netpyne_ui\tests\tut4.py -> build\bdist.win-amd64\wheel\.\netpyne_ui\tests
  copying build\lib\netpyne_ui\tests\tut5.py -> build\bdist.win-amd64\wheel\.\netpyne_ui\tests
  copying build\lib\netpyne_ui\tests\tut6.py -> build\bdist.win-amd64\wheel\.\netpyne_ui\tests
  copying build\lib\netpyne_ui\tests\tut7.py -> build\bdist.win-amd64\wheel\.\netpyne_ui\tests
  copying build\lib\netpyne_ui\tests\__init__.py -> build\bdist.win-amd64\wheel\.\netpyne_ui\tests
  copying build\lib\netpyne_ui\__init__.py -> build\bdist.win-amd64\wheel\.\netpyne_ui
  running install_data
  creating build\bdist.win-amd64\wheel\netpyne_ui-0.5.2.data
  creating build\bdist.win-amd64\wheel\netpyne_ui-0.5.2.data\data
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Sergio\AppData\Local\Temp\pip-install-06m4i9az\netpyne-ui\setup.py", line 41, in <module>
      'netpyne==0.9.1.1'
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\site-packages\wheel\bdist_wheel.py", line 228, in run
      self.run_command('install')
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\site-packages\setuptools\command\install.py", line 61, in run
      return orig.install.run(self)
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\distutils\command\install.py", line 557, in run
      self.run_command(cmd_name)
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\distutils\command\install_data.py", line 56, in run
      dir = convert_path(f[0])
    File "C:\Users\Sergio\Anaconda3\envs\nrn\lib\distutils\util.py", line 112, in convert_path
      raise ValueError("path '%s' cannot end with '/'" % pathname)
  ValueError: path 'geppetto/src/main/webapp/build/' cannot end with '/'

  ----------------------------------------
  Failed building wheel for netpyne-ui
  Running setup.py clean for netpyne-ui
Failed to build netpyne-ui
Installing collected packages: entrypoints, nbconvert, notebook, widgetsnbextension, ipywidgets, pexpect, scipy, jupyter-geppetto, future, matplotlib-scalebar, netpyne, netpyne-ui
  Found existing installation: entrypoints 0.3
Cannot uninstall 'entrypoints'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

(nrn) c:\Users\Sergio>

**Comment by pfeffer90** [comment]
I got the same issue on Linux, Debian 9.

**Comment by afoik** [comment]
Did anybody solve this problem on Windows 10?
