### ISSUE TITLE
Mod file support for simulation in separate process

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#342]

**Comment by lrebscher** [comment]
```
ERROR: Some mechanisms and/or ions were not inserted (for details run with cfg.verbose=True). Make sure the required mod files are compiled.
>>> Traceback (most recent call last):
  File "/Users/user/git/NetPyNE-UI/workspace/experiments/mytest/init.py", line 15, in <module>
    sim.createSimulate(netParams, simConfig)
  File "/Users/user/git/NetPyNE-UI/src/netpyne/netpyne/sim/wrappers.py", line 165, in createSimulate
    (pops, cells, conns, stims, rxd, simData) = sim.create(netParams, simConfig, output=True)
  File "/Users/user/git/NetPyNE-UI/src/netpyne/netpyne/sim/wrappers.py", line 50, in create
    cells = sim.net.createCells()                 # instantiate network cells based on defined populations
  File "/Users/user/git/NetPyNE-UI/src/netpyne/netpyne/network/network.py", line 86, in createCells
    newCells = ipop.createCells() # create cells for this pop using Pop method
  File "/Users/user/git/NetPyNE-UI/src/netpyne/netpyne/network/pop.py", line 79, in createCells
    cells = self.createCellsFixedNum()
  File "/Users/user/git/NetPyNE-UI/src/netpyne/netpyne/network/pop.py", line 175, in createCellsFixedNum
    cells.append(self.cellModelClass(gid, cellTags)) # instantiate Cell object
  File "/Users/user/git/NetPyNE-UI/src/netpyne/netpyne/cell/compartCell.py", line 52, in __init__
    if create: self.create()  # create cell
  File "/Users/user/git/NetPyNE-UI/src/netpyne/netpyne/cell/compartCell.py", line 95, in create
    elif self.tags['cellType'] != propLabel:  # simplified method for defining cell params (when no 'conds')
KeyError: 'cellType'
```
