### ISSUE TITLE
backend tests failing

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#477]
https://g.codefresh.io/build/623b29c7085fe13d82ba54cf?step=BuildingNetPyNE-UI&tab=output&logs=terminal

```
tests/backend/netpyne_model_interpreter_test.py::TestNetPyNEModelInterpreter::test_Hnn
  /home/jovyan/work/NetPyNE-UI/netpyne_ui/netpyne_model_interpreter.py:92: DeprecationWarning: Call to deprecated method createCylinder. (Use the snake case version) -- Deprecated since version 0.6.
    z=float(points[i + 1][2]))))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========= 1 failed, 4 passed, 6 skipped, 19 warnings in 29.52 seconds ==========
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/capture.py", line 441, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/opt/conda/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/sentry_sdk/worker.py", line 128, in _target
    callback()
  File "/opt/conda/lib/python3.7/site-packages/sentry_sdk/transport.py", line 453, in send_event_wrapper
    self._send_event(event)
  File "/opt/conda/lib/python3.7/site-packages/sentry_sdk/transport.py", line 340, in _send_event
    headers={"Content-Type": "application/json", "Content-Encoding": "gzip"},
  File "/opt/conda/lib/python3.7/site-packages/sentry_sdk/transport.py", line 234, in _send_request
    headers=headers,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 442, in _make_request
    httplib_response.length,
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1366, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/opt/conda/lib/python3.7/site-packages/sentry_sdk/integrations/logging.py", line 86, in sentry_patched_callhandlers
    return old_callhandlers(self, record)
Message: '%s://%s:%s "%s %s %s" %s %s'
Arguments: ('https', 'sentry.metacell.us', 443, 'POST', '/api/6/store/', 'HTTP/1.1', 200, 41)
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/capture.py", line 441, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/opt/conda/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/sentry_sdk/worker.py", line 128, in _target
    callback()
  File "/opt/conda/lib/python3.7/site-packages/sentry_sdk/transport.py", line 453, in send_event_wrapper
    self._send_event(event)
  File "/opt/conda/lib/python3.7/site-packages/sentry_sdk/transport.py", line 340, in _send_event
    headers={"Content-Type": "application/json", "Content-Encoding": "gzip"},
  File "/opt/conda/lib/python3.7/site-packages/sentry_sdk/transport.py", line 234, in _send_request
    headers=headers,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 442, in _make_request
    httplib_response.length,
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1366, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/opt/conda/lib/python3.7/site-packages/sentry_sdk/integrations/logging.py", line 86, in sentry_patched_callhandlers
    return old_callhandlers(self, record)
Message: '%s://%s:%s "%s %s %s" %s %s'
Arguments: ('https', 'sentry.metacell.us', 443, 'POST', '/api/6/store/', 'HTTP/1.1', 200, 41)
Removing intermediate container 93e4299014d4
The command '/bin/bash -o pipefail -c pytest tests/backend' returned a non-zero code: 1
[SYSTEM] 
 Message             Failed to build image: netpyne-ui:feature472-b90de06-1648044487577                                 
 Caused by           Container for step title: Building NetPyNE-UI, step type: build, operation: Building image. Failed 
                     with exit code: 1                                                                                  
 Documentation Link  https://codefresh.io/docs/docs/codefresh-yaml/steps                                                
 Exit code           1                                                                                                  
 Name                NonZeroExitCodeError    
```

**Comment by ddelpiano** [comment]
![scrnli_06_04_2022_15-52-10](https://user-images.githubusercontent.com/37704177/162003400-64f59dbc-1a84-4b57-9353-0fdc057117d8.png)

Latest development show still a wrong version for the UI

**Comment by enicolasgomez** [comment]
@ddelpiano the version has been bumped on release/080 branch, it's expected that development has the old version as the branch has not yet been merged

**Comment by enicolasgomez** [comment]
@ddelpiano how should I replicate this? maybe?
`sh tests/deployment/build.sh`

**Comment by enicolasgomez** [comment]
if that's the one, it worked for me...

```
 => [5/5] COPY . .                                                                                                                                                                                 0.0s 
 => exporting to image                                                                                                                                                                             4.9s 
 => => exporting layers                                                                                                                                                                            4.9s 
 => => writing image sha256:09ccdd12f82f998e2c43976f4463bedd0a9d93c3377acc87e58a381173926d41                                                                                                       0.0s 
 => => naming to docker.io/library/netpyne-ui-e2e   
```

**Comment by enicolasgomez** [comment]
@ddelpiano was able to reproduce this, it has to do with sentry plugging and killing the pipeline when pytest is erroring out. Didn't find a solution yet but according to this:

https://github.com/getsentry/sentry-symfony/issues/46

setting a null dns on sentry's configuration while running tests would do the trick

**Comment by enicolasgomez** [comment]
after setting the null DNS config for backend tests it's not erroring out anymore besides some tests still fail but those are unrelated to the described issue and the scripts exits gracefully

`11 failed, 73 passed, 12 skipped, 2497 warnings, 8 error in 99.87 seconds `
